GET http://localhost:3000/products.json

###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Cal's Saber",
  "price": 350,
  "quantity": 2,
  "description": "A saber belonging to the escaped padawan Cal Kestis; silver hilt, cracked purple kyber crystal.",
  "quantity": 1
}

###
PATCH http://localhost:3000/products/6.json
Content-Type: application/json

{
  "name": "First Blade",
  "price": 10000,
  "quantity": 1,
  "description": "The First Blade was an ancient weapon that served as the foundation for all modern lightsabers."
}

###
DELETE http://localhost:3000/products/4

###
POST http://localhost:3000/orders
Content-Type: application/json

{

}

###
GET http://localhost:3000/orders/1.json

###
GET http://localhost:3000/orders.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Slartibartfast",
  "email": "hitch@hikers2.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "hitch@hikers2.com",
  "password": "password"
}

### Photos create
POST http://localhost:3000/photos.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NDg1NzQ0MTl9.WZXEfZHToRkIpM5jrOdh8gtD5AjNeF-2GaC2azRdqOk
Content-Type: application/json

{
  "name": "Test name",
  "width": 640,
  "height": 480
}
###
POST http://localhost:3000/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NDg1NzQ0MTl9.WZXEfZHToRkIpM5jrOdh8gtD5AjNeF-2GaC2azRdqOk
Content-Type: application/json

{
  "user_id": 6,
  "product_id": 4,
  "quantity": 1,
  "status": "carted"
}
