GET http://localhost:3000/products.json

###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Cal's Saber",
  "price": 350,
  "quantity": 2,
  "description": "A saber belonging to the escaped padawan Cal Kestis; silver hilt, cracked purple kyber crystal.",
  "quantity": 1
}

###
PATCH http://localhost:3000/products/6.json
Content-Type: application/json

{
  "name": "First Blade",
  "price": 10000,
  "quantity": 1,
  "description": "The First Blade was an ancient weapon that served as the foundation for all modern lightsabers."
}

###
DELETE http://localhost:3000/products/4

###
POST http://localhost:3000/orders
Content-Type: application/json

{

}

###
GET http://localhost:3000/orders/1.json

###
GET http://localhost:3000/orders.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Slighty Bobfost",
  "email": "hitch@hikers.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Photos create
POST http://localhost:3000/photos.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json

{
  "name": "Test name",
  "width": 640,
  "height": 480
}