@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2NDk5OTY2Njd9.WIlUMyOlKc5hMg0OuVFCTpZ7Ze3VYKk6SkQtKpBTamk


GET http://localhost:3000/products.json

###
GET http://localhost:3000/products/5.json

###
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Scouter",
  "price": 3500,
  "quantity": 38,
  "description": "Detects power levels.",
  "supplier_id": 23,
  "image": "https://i.ytimg.com/vi/ZZV4tMVi0-M/maxresdefault.jpg"
}

###
PATCH http://localhost:3000/products/7.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Saiyan Scouter",
  "price": 3500,
  "description": "Detects power levels.",
  "quantity": 38
}

###
DELETE http://localhost:3000/products/8

###
POST http://localhost:3000/orders
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": 2,
  "product_id": 4,
  "quantity": 3,
  "subtotal": 450,
  "tax": 50,
  "total": 500
}

###
GET http://localhost:3000/orders/1.json

###
GET http://localhost:3000/orders.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "The Doctor",
  "email": "dw@who.tardis",
  "password": "password",
  "password_confirmation": "password",
  "admin": true
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "dw@who.tardis",
  "password": "password"
}

### Photos create
POST http://localhost:3000/photos.json
Authorization: Bearer {{jwt}}

Content-Type: application/json

{
  "name": "Test name",
  "width": 640,
  "height": 480
}
###
POST http://localhost:3000/orders/
Authorization: Bearer {{jwt}}

Content-Type: application/json

{
  "user_id": 6,
  "product_id": 4,
  "quantity": 1,
  "status": "carted"
}
